### ISSUE TITLE
Redirect not working on Nyxt 2-pre-release-5

### ISSUE THREAD

**Issue by ghost** [kssytsrk/nx-freestance-handler#12]
Hi!
I am on ArchLinux, using this AUR package: https://aur.archlinux.org/packages/nyxt
The Nyxt version it installs is: 2-pre-release-5
I have added exactly what is in the README to my init.lisp, but no redirection work..
It only works if I manually add hosts to redirect like:
```
(defparameter old-reddit-handler
	(url-dispatching-handler
 		'old-reddit-dispatcher
		(match-host "www.reddit.com")
		(lambda (url)
			(quri:copy-uri url :host "old.reddit.com"))))
(defvar *my-request-resource-handlers* (list old-reddit-handler))

...
```
instead of the provided example: `(defvar *my-request-resource-handlers* '())`

**Comment by kssytsrk** [comment]
Hello. I just committed a (potential) fix, please `git pull` the repo and try the example in README.md, does it work now?

**Comment by ghost** [comment]
Just tried.. Still nothing I'm afraid.
Using what I sent above still redirect me to old.reddit. As for the other domains nothing even with clean example from README

**Comment by kssytsrk** [comment]
Ehh, no idea what could be going wrong here, all of the nx-freestance-handler code works with no problems if copy-pasted straight into the init file (btw you can do that, if you need the plugin's features ASAP, just make sure to clean up all the nx-freestance-handler package specifiers).

Try starting Nyxt from console (with the code from README.md in the init file), does it spit out something similar to the log below or is it more meaningful?

```
<INFO> [22:07:00] Listening to socket "/home/username/.local/share/nyxt/nyxt.socket".
Nyxt version 2-pre-release-5-538-g3c68b164
<INFO> [22:07:00] Loading Lisp file "/home/username/.config/nyxt/auto-config.lisp".
<INFO> [22:07:00] Loading Lisp file "/home/username/.config/nyxt/init.lisp".
; 
; compilation unit aborted
;   caught 1 fatal ERROR condition

```

**Comment by ghost** [comment]
Just did everything clean.
```
rm -r ~/common-lisp
mkdir ~/common-lisp && cd ~/common-lisp
git clone https://github.com/kssytsrk/nx-freestance-handler

rm -rf ~/.config/nyxt ~/.cache/nyxt ~/.local/share/nyxt
mkdir ~/.config/nyxt
nvim ~/.config/nyxt/init.lisp                       # paste here
nvim ~/.config/nyxt/freestance.lisp           # paste here
```

Now starting from terminal I get:
```
<INFO> [22:42:08] Listening to socket "/home/qwuy/.local/share/nyxt/nyxt.socket".
Nyxt version 2-pre-release-5
<INFO> [22:42:08] Loading Lisp file "/home/qwuy/.config/nyxt/init.lisp".
;
; compilation unit aborted
;   caught 1 fatal ERROR condition
```
Nothing more meaningful :(

**Comment by kssytsrk** [comment]
Okay, I think I got it. Here's what you need to do to make it work (well, that works for me):

1. `git pull` from the repo, and follow the instructions in README.md for the init file
2. Run `sbcl` from console (it would work in SLY/SLIME too, I'm just not sure you use any of them), and execute `(asdf:clear-source-registry)`. This cleans the cache.
3. Run `nyxt`. Redirection should work now.

**Comment by ghost** [comment]
Now everything works :)
Thanks a lot for this!
Have a good day
