### ISSUE TITLE
Wrong use of load-after-system

### ISSUE THREAD

**Issue by Ambrevar** [kssytsrk/nx-freestance-handler#7]
The first argument of load-after-system is the system to load.
The second argument is a file to load.

On master, you can leverage the new nyxt-init-file and do something like this:

(load-after-system :invidious-handler
                   (nyxt-init-file "invidious.lisp"))

which will load the configuration from `~/.config/nyxt/invidious.lisp` by default.

**Comment by kssytsrk** [comment]
Oh, I see, thanks for the heads-up, I'll fix the readme. So the issue (well, it seems like a bit of an issue to me... not sure) of having to put the extensions into `~/common-lisp` but not in an arbitrary/nyxt-specific location is still not solved yet?

**Comment by Ambrevar** [comment]
Indeed, for now Nyxt uses the default ASDF registry.

**Comment by kssytsrk** [comment]
Okay. Fixed the readme, does everything look alright now (well, for me it works, so...)?

**Comment by Ambrevar** [comment]
With regard to this issue, yes, the instructions are correct now!

**Comment by kssytsrk** [comment]
I'll close this, then.
